# Generated by Django 3.1.7 on 2021-03-11 14:05

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('clientOrderId', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('filled_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('symbol', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=5)),
                ('status', django_fsm.FSMField(choices=[('created', 'created'), ('filled', 'filled'), ('cancelled', 'cancelled'), ('partially_filled', 'partially_filled')], default='created', max_length=50)),
            ],
        ),
    ]
